name: Backend CI/CD

on:
  push:
    branches:
      - main  # Trigger this workflow only on changes to the 'main' branch.
  pull_request:
    branches:
      - main  # Trigger on PRs targeting 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Fetches your code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Ensure you are using the correct Node.js version.

    - name: Install dependencies
      run: |
        cd spotify_backend
        npm install  # Assuming your backend has a package.json file.

    # - name: Run tests
    #   run: |
    #     cd spotify_backend
    #     npm test  # Make sure you have tests defined in your 'backend' package.

    - name: Build project
      run: |
        cd spotify_backend
        npm run build  # Adjust according to your build setup.

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build  # Deploy only after successful build.

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Set up Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '18'

  #   - name: Deploy to server
  #     run: |
  #       cd backend
  #       # Add your deployment steps here (e.g., SSH to server, Docker, etc.)
  #       # Example:
  #       # ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server "cd /path/to/app && git pull && npm install && pm2 restart all"

